### PR TITLE
Use ArrowUp and ArrowDown key for moving between blocks

### LINKED ISSUE #9: moving through blocks (text and code) with arrow keys
the idea is hook up to codemirror's goup and godown event, check if cursor is at the begin/end of buffer and focus on next/previous block

### PR DESCRIPTION
**Pull request by thangngoc89**
Fixes #9 
cc @matthiaskern 

This is an early preview of that functionality. I want to discuss a about UX before merging this. 
Currently, when calling `editor.focus()`, CodeMirror will put cursor at last focus position. Do you thing that would be annoying? Do we need to adjust cursor position as well? (put cursor at (0, 0) in next block on ArrowDown and (lastLine, lastChar) in previous block on ArrowUp)

You can see the this PR in production here: https://rtop-frxlpjtusg.now.sh

---

Note to self:

to set cursor at the end of existing content: `cmInstance.setCursor(cmInstance.lineCount(), 0);`

### CODE REVIEW

**Comment by matthiaskern** [comment]
Putting the cursor at the last focus position makes sense, but is definitely confusing when it happens at first. To me the second option seems more intuitive from the get go. @thangngoc89

**Comment by thangngoc89** [comment]
@matthiaskern Thank you for your input. I'll push the code in a moment

**Comment by thangngoc89** [comment]
@matthiaskern I updated this PR. ;)

**Comment by thangngoc89** [comment]
Here you go https://rtop-cqfjwixveo.now.sh

**Pull request merged**
